### ISSUE TITLE
唐久便利报错是因为已经签到了吗

### ISSUE THREAD

**Issue by mem4tgo** [AKA-Cigma/QLscripts#6]
Traceback (most recent call last):
  File "/ql/data/scripts/唐久.py", line 72, in <module>
    data = request_json(urls[0], headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/唐久.py", line 50, in request_json
    raw_response = response.content.decode('utf-8')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 2: invalid start byte

**Comment by mem4tgo** [comment]
## 开始执行... 2024-12-23 00:25:00

import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'posix' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
# installing zipimport hook
import 'time' # <class '_frozen_importlib.BuiltinImporter'>
import 'zipimport' # <class '_frozen_importlib.FrozenImporter'>
# installed zipimport hook
# /usr/lib/python3.11/encodings/__pycache__/__init__.cpython-311.pyc matches /usr/lib/python3.11/encodings/__init__.py
# code object from '/usr/lib/python3.11/encodings/__pycache__/__init__.cpython-311.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <class '_frozen_importlib.FrozenImporter'>
# /usr/lib/python3.11/encodings/__pycache__/aliases.cpython-311.pyc matches /usr/lib/python3.11/encodings/aliases.py
# code object from '/usr/lib/python3.11/encodings/__pycache__/aliases.cpython-311.pyc'
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0x757d98de50>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0x757d97a2d0>
# /usr/lib/python3.11/encodings/__pycache__/utf_8.cpython-311.pyc matches /usr/lib/python3.11/encodings/utf_8.py
# code object from '/usr/lib/python3.11/encodings/__pycache__/utf_8.cpython-311.pyc'
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0x757d97bc50>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
import '_abc' # <class '_frozen_importlib.BuiltinImporter'>
import 'abc' # <class '_frozen_importlib.FrozenImporter'>
import 'io' # <class '_frozen_importlib.FrozenImporter'>
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <class '_frozen_importlib.FrozenImporter'>
import '_collections_abc' # <class '_frozen_importlib.FrozenImporter'>
import 'genericpath' # <class '_frozen_importlib.FrozenImporter'>
import 'posixpath' # <class '_frozen_importlib.FrozenImporter'>
import 'os' # <class '_frozen_importlib.FrozenImporter'>
import '_sitebuiltins' # <class '_frozen_importlib.FrozenImporter'>
Processing user site-packages
Processing global site-packages
Adding directory: '/usr/lib/python3.11/site-packages'
Processing .pth file: '/usr/lib/python3.11/site-packages/distutils-precedence.pth'
# /usr/lib/python3.11/site-packages/_distutils_hack/__pycache__/__init__.cpython-311.pyc matches /usr/lib/python3.11/site-packages/_distutils_hack/__init__.py
# code object from '/usr/lib/python3.11/site-packages/_distutils_hack/__pycache__/__init__.cpython-311.pyc'
import '_distutils_hack' # <_frozen_importlib_external.SourceFileLoader object at 0x757d6f2a50>
import 'site' # <class '_frozen_importlib.FrozenImporter'>
Python 3.11.8 (main, Feb 19 2024, 22:58:08) [GCC 12.2.1 20220924] on linux
Type "help", "copyright", "credits" or "license" for more information.
# /usr/lib/python3.11/json/__pycache__/__init__.cpython-311.pyc matches /usr/lib/python3.11/json/__init__.py
# code object from '/usr/lib/python3.11/json/__pycache__/__init__.cpython-311.pyc'
# /usr/lib/python3.11/json/__pycache__/decoder.cpython-311.pyc matches /usr/lib/python3.11/json/decoder.py
# code object from '/usr/lib/python3.11/json/__pycache__/decoder.cpython-311.pyc'
# /usr/lib/python3.11/re/__pycache__/__init__.cpython-311.pyc matches /usr/lib/python3.11/re/__init__.py
# code object from '/usr/lib/python3.11/re/__pycache__/__init__.cpython-311.pyc'
# /usr/lib/python3.11/__pycache__/enum.cpython-311.pyc matches /usr/lib/python3.11/enum.py
# code object from '/usr/lib/python3.11/__pycache__/enum.cpython-311.pyc'
# /usr/lib/python3.11/__pycache__/types.cpython-311.pyc matches /usr/lib/python3.11/types.py
# code object from '/usr/lib/python3.11/__pycache__/types.cpython-311.pyc'
import 'types' # <_frozen_importlib_external.SourceFileLoader object at 0x757d70aa10>
# /usr/lib/python3.11/__pycache__/operator.cpython-311.pyc matches /usr/lib/python3.11/operator.py
# code object from '/usr/lib/python3.11/__pycache__/operator.cpython-311.pyc'
import '_operator' # <class '_frozen_importlib.BuiltinImporter'>
import 'operator' # <_frozen_importlib_external.SourceFileLoader object at 0x757d715850>
# /usr/lib/python3.11/__pycache__/functools.cpython-311.pyc matches /usr/lib/python3.11/functools.py
# code object from '/usr/lib/python3.11/__pycache__/functools.cpython-311.pyc'
# /usr/lib/python3.11/collections/__pycache__/__init__.cpython-311.pyc matches /usr/lib/python3.11/collections/__init__.py
# code object from '/usr/lib/python3.11/collections/__pycache__/__init__.cpython-311.pyc'
import 'itertools' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/lib/python3.11/__pycache__/keyword.cpython-311.pyc matches /usr/lib/python3.11/keyword.py
# code object from '/usr/lib/python3.11/__pycache__/keyword.cpython-311.pyc'
import 'keyword' # <_frozen_importlib_external.SourceFileLoader object at 0x757d74bd10>
# /usr/lib/python3.11/__pycache__/reprlib.cpython-311.pyc matches /usr/lib/python3.11/reprlib.py
# code object from '/usr/lib/python3.11/__pycache__/reprlib.cpython-311.pyc'
import 'reprlib' # <_frozen_importlib_external.SourceFileLoader object at 0x757d768850>
import '_collections' # <class '_frozen_importlib.BuiltinImporter'>
import 'collections' # <_frozen_importlib_external.SourceFileLoader object at 0x757d741350>
import '_functools' # <class '_frozen_importlib.BuiltinImporter'>
import 'functools' # <_frozen_importlib_external.SourceFileLoader object at 0x757d720cd0>
import 'enum' # <_frozen_importlib_external.SourceFileLoader object at 0x757d708610>
# /usr/lib/python3.11/re/__pycache__/_compiler.cpython-311.pyc matches /usr/lib/python3.11/re/_compiler.py
# code object from '/usr/lib/python3.11/re/__pycache__/_compiler.cpython-311.pyc'
import '_sre' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/lib/python3.11/re/__pycache__/_parser.cpython-311.pyc matches /usr/lib/python3.11/re/_parser.py
# code object from '/usr/lib/python3.11/re/__pycache__/_parser.cpython-311.pyc'
# /usr/lib/python3.11/re/__pycache__/_constants.cpython-311.pyc matches /usr/lib/python3.11/re/_constants.py
# code object from '/usr/lib/python3.11/re/__pycache__/_constants.cpython-311.pyc'
import 're._constants' # <_frozen_importlib_external.SourceFileLoader object at 0x757d787ed0>
import 're._parser' # <_frozen_importlib_external.SourceFileLoader object at 0x757d785590>
# /usr/lib/python3.11/re/__pycache__/_casefix.cpython-311.pyc matches /usr/lib/python3.11/re/_casefix.py
# code object from '/usr/lib/python3.11/re/__pycache__/_casefix.cpython-311.pyc'
import 're._casefix' # <_frozen_importlib_external.SourceFileLoader object at 0x757d78ed90>
import 're._compiler' # <_frozen_importlib_external.SourceFileLoader object at 0x757d776690>
# /usr/lib/python3.11/__pycache__/copyreg.cpython-311.pyc matches /usr/lib/python3.11/copyreg.py
# code object from '/usr/lib/python3.11/__pycache__/copyreg.cpython-311.pyc'
import 'copyreg' # <_frozen_importlib_external.SourceFileLoader object at 0x757d78ffd0>
import 're' # <_frozen_importlib_external.SourceFileLoader object at 0x757d6fea10>
# /usr/lib/python3.11/json/__pycache__/scanner.cpython-311.pyc matches /usr/lib/python3.11/json/scanner.py
# code object from '/usr/lib/python3.11/json/__pycache__/scanner.cpython-311.pyc'
# extension module '_json' loaded from '/usr/lib/python3.11/lib-dynload/_json.cpython-311-aarch64-linux-musl.so'
# extension module '_json' executed from '/usr/lib/python3.11/lib-dynload/_json.cpython-311-aarch64-linux-musl.so'
import '_json' # <_frozen_importlib_external.ExtensionFileLoader object at 0x757d795110>
import 'json.scanner' # <_frozen_importlib_external.SourceFileLoader object at 0x757d78ff50>
import 'json.decoder' # <_frozen_importlib_external.SourceFileLoader object at 0x757d6fd310>
# /usr/lib/python3.11/json/__pycache__/encoder.cpython-311.pyc matches /usr/lib/python3.11/json/encoder.py
# code object from '/usr/lib/python3.11/json/__pycache__/encoder.cpython-311.pyc'
import 'json.encoder' # <_frozen_importlib_external.SourceFileLoader object at 0x757d6ff710>
import 'json' # <_frozen_importlib_external.SourceFileLoader object at 0x757d6f3ed0>
# clear builtins._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.__interactivehook__
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
# cleanup[2] removing sys
# cleanup[2] removing builtins
# cleanup[2] removing _frozen_importlib
# cleanup[2] removing _imp
# cleanup[2] removing _thread
# cleanup[2] removing _warnings
# cleanup[2] removing _weakref
# cleanup[2] removing _io
# cleanup[2] removing marshal
# cleanup[2] removing posix
# cleanup[2] removing _frozen_importlib_external
# cleanup[2] removing time
# cleanup[2] removing zipimport
# destroy zipimport
# cleanup[2] removing _codecs
# cleanup[2] removing codecs
# cleanup[2] removing encodings.aliases
# cleanup[2] removing encodings
# destroy encodings
# cleanup[2] removing encodings.utf_8
# cleanup[2] removing _signal
# cleanup[2] removing _abc
# cleanup[2] removing abc
# cleanup[2] removing io
# cleanup[2] removing __main__
# destroy __main__
# cleanup[2] removing _stat
# cleanup[2] removing stat
# cleanup[2] removing _collections_abc
# cleanup[2] removing genericpath
# cleanup[2] removing posixpath
# cleanup[2] removing os.path
# cleanup[2] removing os
# cleanup[2] removing _sitebuiltins
# cleanup[2] removing _distutils_hack
# destroy _distutils_hack
# cleanup[2] removing site
# destroy site
# cleanup[2] removing types
# destroy types
# cleanup[2] removing _operator
# cleanup[2] removing operator
# destroy operator
# cleanup[2] removing itertools
# cleanup[2] removing keyword
# destroy keyword
# cleanup[2] removing reprlib
# destroy reprlib
# cleanup[2] removing _collections
# cleanup[2] removing collections
# destroy collections
# cleanup[2] removing _functools
# cleanup[2] removing functools
# cleanup[2] removing enum
# cleanup[2] removing _sre
# cleanup[2] removing re._constants
# cleanup[2] removing re._parser
# cleanup[2] removing re._casefix
# cleanup[2] removing re._compiler
# cleanup[2] removing copyreg
# cleanup[2] removing re
# cleanup[2] removing _json
# cleanup[2] removing json.scanner
# cleanup[2] removing json.decoder
# cleanup[2] removing json.encoder
# cleanup[2] removing json
# destroy json
# destroy _signal
# destroy _sitebuiltins
# destroy io
# destroy json.decoder
# destroy json.encoder
# destroy json.scanner
# destroy enum
# destroy re._constants
# destroy re._casefix
# destroy re._compiler
# destroy functools
# destroy copyreg
# destroy _collections_abc
# destroy _operator
# destroy itertools
# destroy _collections
# destroy _functools
# destroy re._parser
# destroy _sre
# destroy re
# destroy _json
# cleanup[3] wiping os
# destroy abc
# destroy posixpath
# cleanup[3] wiping genericpath
# cleanup[3] wiping stat
# cleanup[3] wiping _stat
# destroy _stat
# cleanup[3] wiping _abc
# cleanup[3] wiping encodings.utf_8
# cleanup[3] wiping encodings.aliases
# cleanup[3] wiping codecs
# cleanup[3] wiping _codecs
# cleanup[3] wiping time
# cleanup[3] wiping _frozen_importlib_external
# cleanup[3] wiping posix
# cleanup[3] wiping marshal
# cleanup[3] wiping _io
# cleanup[3] wiping _weakref
# cleanup[3] wiping _warnings
# cleanup[3] wiping _thread
# cleanup[3] wiping _imp
# cleanup[3] wiping _frozen_importlib
# destroy _weakref
# cleanup[3] wiping sys
# cleanup[3] wiping builtins
# destroy _thread
# destroy _frozen_importlib_external
# destroy _imp
# destroy io
# destroy marshal
# destroy time
# destroy _warnings
# destroy os
# destroy stat
# destroy genericpath
# destroy posix
# destroy _abc
# destroy _frozen_importlib
# destroy codecs
# destroy sys
# destroy encodings.aliases
# destroy encodings.utf_8
# destroy _codecs
# destroy builtins
# clear sys.audit hooks

获取到 1 个账号

=======开始执行账号1=======

Traceback (most recent call last):
  File "/ql/data/scripts/tjbl.swap.py", line 72, in <module>
    data = request_json(urls[0], headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/tjbl.swap.py", line 50, in request_json
    raw_response = response.content.decode('utf-8')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 2: invalid start byte

**Comment by AKA-Cigma** [comment]
感觉是ck抓的不对

**Comment by mem4tgo** [comment]
> 感觉是ck抓的不对

对了。但是还是

=======开始执行账号1=======

请求出错：

'utf-8' codec can't decode byte 0x80 in position 2: invalid start byte
请求出错：

'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte
请求出错：

'utf-8' codec can't decode byte 0xa3 in position 1: invalid start byte
PUSHPLUS 服务启动

**Comment by mem4tgo** [comment]
> 感觉是ck抓的不对

是需要json、os库吗

**Comment by mem4tgo** [comment]
> 感觉是ck抓的不对

还是py版本不对。是3以上才能utf编码吗

**Comment by mem4tgo** [comment]
> 感觉是ck抓的不对

Python抓取数据时，如果header添加了

accept_encoding = 'gzip, deflate, br'
无论如何转码都会出现 'utf-8' codec can't decode byte 0xxx in position 1: invalid start byte 的错误

只需将 accept_encoding = '' 设置为空即可

原因：

本地接收压缩格式的数据，服务器传过来压缩格式gzip的文件，而解压这种gzip文件只能用deflate算法，浏览器能够自动解压，程序却不能自动解压gzip，需要额外进行设置才行。



————————————————————————————————————————
因为这个代码出错的。怎么设置才可以呢

**Comment by mem4tgo** [comment]
UP。这个代码是解析 JSON 数据的错误。
